#########服务器环境变量############
server: 
  port: 8082
#########Spring环境变量########### 
spring: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/developer?useUnicode=true&characterEncoding=utf-8
    username: roo t
    password:  
#    driver-class-name: com.mysql.jdbc.Driver

logging: 
  level:
    root: debug
    org.springframework: error
    org.hibernate: error
    org.apache: error